Actarium/urls.py
#encoding:utf-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # to change:
    url(r'^contact/', include('contact_form.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^oauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^meal/', include(admin.site.urls)),
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

for app in settings.APPS:
    try:
        appurls = __import__(app + ".urls", fromlist=['urls'])
        if hasattr(appurls, "name"):
            ns = ""
            if hasattr(appurls, "namespace"):
                ns = appurls.namespace
            urlpatterns += patterns('',
                url(r'^' + appurls.name + '/', include(appurls.urlpatterns, namespace=ns)),
            )
        else:
            urlpatterns += appurls.urlpatterns
    except Exception as e:
        # print "Error: ",app, e
        # print type(e)
        if not (str(e) =="No module named urls"):
            raise e


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

urlpatterns += patterns("",
    url(r'^$', 'actarium_apps.organizations.views.listOrgs', name="list_orgs"),
)

actarium_apps/api/urls.py
# -*- coding:utf-8 -*-

# import django elements
from django.conf.urls import patterns, include, url

# import rest_framework elements
from rest_framework.routers import DefaultRouter

# import custom elements
from .viewsets import UserViewSet


router = DefaultRouter()
router.register(r'users', UserViewSet)


name = "rest"
# namespace = 'rest_framework'

urlpatterns = patterns('',
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
)

actarium_apps/core/urls.py
from django.conf.urls import url, patterns
from .views import *
from .views_ajax import *

name = "actarium"
namespace = 'core'

urlpatterns = patterns('',
    url(r'^services/(?P<slug_org>[-\w]+)/$', read_organization_services, name='read_organization_services'),
    url(r'^get_price/$', get_total_price, name='get_total_price'),
    url(r'^get_discount_value/$', get_discount_value, name='get_discount_value'),
    url(r'^search_minutes/$', search_minutes, name='search_minutes'),
)

actarium_apps/customers_services/urls.py
from django.conf.urls import url, patterns
from .views import read_pricing, read_orders
from .views_ajax import approve_order

name = "services"
namespace='services'

urlpatterns = patterns('',
    url(r'^pricing/(?P<slug_org>[-\w]+)/$', read_pricing, name='read_pricing'),
    url(r'^admin_orders/$', read_orders, name='admin_orders'),
    url(r'^approve_order/$', approve_order, name='approve_order'),
)

actarium_apps/customers_services/models.py
#encoding:utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .managers import *

# common fields: for use it uncomment the class below 
# and change "models.Model" for "CommonFields" in each class model that you want, 
# as well comment the attrs "is_active","created" and "modified" in each class 

#class CommonFields(models.Model):
#    is_active = models.BooleanField(default=True)
#    created = models.DateTimeField(auto_now_add=True)
#    modified = models.DateTimeField(auto_now=True)
#
#    class meta:
#        abstract = True

# models that require fixtures


class OrderStatus(models.Model):
    code = models.CharField(max_length=300, verbose_name=_(u"Código"))
    name = models.CharField(max_length=300, verbose_name=_("Nombre"))
    description = models.TextField(blank=True, verbose_name=_(u"Descripción"))
    is_active = models.BooleanField(default=True)
    
    objects = GenericManager()
    
    def __unicode__(self):
        return u"[%s] %s" % (self.code,self.name)


class Periods(models.Model):
    code = models.CharField(max_length=300, verbose_name=_(u"Código"))
    name = models.CharField(max_length=300, verbose_name=_("Nombre"))
    is_active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return u"[%s] %s" % (self.code,self.name)


# models that require Django-Admin


class ServicesCategories(models.Model,):
    code = models.CharField(max_length=100, verbose_name=_(u"Código"))
    name = models.CharField(max_length=300, verbose_name=_("Nombre"))
    description = models.TextField(blank=True, verbose_name=_(u"Descripción"))
    
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    objects = GenericManager()

    def __unicode__(self):
        return u"[%s] %s" % (self.code,self.name)


class PaymentMethods(models.Model):
    code = models.CharField(max_length=100, verbose_name=_(u"Código"))
    name = models.CharField(max_length=300, verbose_name=_("Nombre"))
    description = models.TextField(blank=True, verbose_name=_(u"Descripción"))
    
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    objects = GenericManager()

    def __unicode__(self):
        return u"%s" % (self.name)
    
    
class Services(models.Model):
    code = models.CharField(max_length=300, verbose_name=_(u"Código"))
    name = models.CharField(max_length=300, verbose_name=_("Nombre"))
    description = models.TextField(blank=True, verbose_name=_(u"Descripción"))
    price_per_period = models.FloatField(verbose_name=_(u"Precio por período"))
    
    period = models.ForeignKey(Periods, related_name='%(class)s_period', verbose_name=_(u"Período"))
    service_category = models.ForeignKey(ServicesCategories, related_name='%(class)s_service_category', verbose_name=_(u"Categoría"))

    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    objects = ServicesManager()
    
    def __unicode__(self):
        return u"[%s-%s] %s ($%.0f/%s)" % (self.service_category,self.code, self.name,self.price_per_period,self.period)

    def price_per_period_int(self):
        return int(self.price_per_period)

    price_per_period_int = property(price_per_period_int)
    
    
# Models for runtime


class CustomersServices(models.Model):
    quantity = models.IntegerField(verbose_name=_("Cantidad"))
    date_expiration = models.DateField(verbose_name=_("Fecha de vencimiento"))
    
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    objects = CustomersServicesManager()
    
    def get_order_active(self):
        order_related = self.orderitems_customer_service.get_or_none(order__status_id=2)
        if order_related:
            service_name =  order_related
        else:
            service_name = None 
        return service_name

    def service_name(self):
        service = self.get_order_active().service
        if service:
            service_name =  service.service_category.name
        else:
            service_name = None #_(u"Servicio no asignado a ninguna orden")
        return service_name
    
    def service_category(self):
        service = self.get_order_active().service
        if service:
            service_category =  service.service_category
        else:
            service_category = None
        return service_category
    
    def __unicode__(self):
        return u"[%s] %s - %s" % (self.service_name(),self.quantity, self.date_expiration)
    


class Addresses(models.Model):
    country = models.CharField(max_length=300, verbose_name=_(u"País"), null=False, blank=True)
    province = models.CharField(max_length=300, verbose_name=_("Departamento"), null=False, blank=True)
    city = models.CharField(max_length=300, verbose_name=_("Ciudad"), null=False, blank=True)

    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return u"%s/%s/%s" % (self.country, self.province, self.city)
    
    
class Customers(models.Model):
    name = models.CharField(max_length=300, verbose_name=_("Nombre"))
    phone = models.CharField(max_length=300, verbose_name=_(u"Teléfono"), null=False, blank=True)
    email = models.CharField(max_length=300, verbose_name=_("Correo"))
 
    address = models.OneToOneField(Addresses, verbose_name=_("Dirección"))
    payment_methods = models.ManyToManyField(PaymentMethods)
    
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.email)
 
 
class CustomerOrders(models.Model):
    status = models.ForeignKey(OrderStatus, related_name='%(class)s_status', verbose_name=_("Estado"))
    customer = models.ForeignKey(Customers, related_name='%(class)s_customer', verbose_name=_("Cliente"))
    
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
 
    def __unicode__(self):
        return u"[%s] %s" % (self.status, self.customer)
 
 
class OrderItems(models.Model):
    order_quantity = models.IntegerField(verbose_name=_("Cantidad"))
    number_of_periods = models.IntegerField(verbose_name=_(u"Número de periodos"))
    discount = models.IntegerField(verbose_name=_("Descuento"))
    
    service = models.ForeignKey(Services, related_name='%(class)s_service', verbose_name=_("Servicio"))
    order = models.ForeignKey(CustomerOrders, related_name='%(class)s_order', verbose_name=_("Orden del cliente"))
    customer_service = models.ForeignKey(CustomersServices, related_name='%(class)s_customer_service', verbose_name=_("Servicio del cliente"))
    
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    objects = OrderItemsManager()
    
    def get_price_per_period(self):
        return int(self.order_quantity*self.service.price_per_period)

    def get_total_price(self):
        return int((self.get_price_per_period()*self.number_of_periods) - self.discount)


    def __unicode__(self):
        return u"%s - %s" % (self.service, self.order)

actarium_apps/customers_services/views.py
#encoding:utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from actarium_apps.core.models import Packages
from actarium_apps.core.models import ServicesRanges
from actarium_apps.core.models import DiscountCodes
from actarium_apps.core.forms import OrderMembersServiceForm

from .models import *



@login_required()
def read_pricing(request, slug_org):
    from apps.website.views import getGlobalVar
        
    if slug_org:
        org = request.user.organizationsuser_user.get_org(slug=slug_org)
        if org and org.has_user_role(request.user,'is_creator'):
            is_creator = True

        id_package = request.GET.get("id_package")
        if id_package:
            show_modal=True
        FREE_PACKAGE_ID = getGlobalVar("FREE_PACKAGE_ID")
        packages = Packages.objects.get_all_active().order_by('code').exclude(id=FREE_PACKAGE_ID)

        services_list = Services.objects.filter(service_category__code="C001", is_active=True).order_by("-price_per_period")

        services_categories = ServicesCategories.objects.filter(is_active=True)

        if request.method == "POST":
            order_members_form = OrderMembersServiceForm(request.POST,user_customer=request.user)
            if order_members_form.is_valid():
                payment_method = order_members_form.cleaned_data['payment_method']
                if payment_method.id == 1:
                    package = order_members_form.cleaned_data['packages']
                    number_of_members = package.number_of_members
                    number_of_months = order_members_form.cleaned_data['number_of_months']
                    discount_code = order_members_form.cleaned_data['discount']
                    customer_services = org.organizationservices_organization.get_members_service_active()
                    service = ServicesRanges.objects.get_service(number_of_members)
                    discount_value_obj = DiscountCodes.objects.get_or_none(code=discount_code,is_active=True)
                    discount_value = discount_value_obj.value if discount_value_obj else  0

                    if int(number_of_months) >= 12:
                        base = float(number_of_members)*service.price_per_period
                        base = base*float(number_of_months)
                        discount_value = discount_value + base*0.05

                    order_id, message = OrderItems.objects.create_members_order(number_of_members=number_of_members,number_of_months=number_of_months,
                                                customer_services=customer_services,service=service,discount_value=discount_value,user=request.user)

                    if order_id:
                        if discount_value_obj:
                            discount_value_obj.is_active= False
                            discount_value_obj.save()
                        return HttpResponseRedirect(reverse("core:read_organization_services",args=(org.slug,))+"?order="+str(order_id))
                    else:
                        error = message
                else:
                    error = _(u"El método de pago seleccionado no existe")
            else:                
                show_modal=True

        else:
            order_members_form  = OrderMembersServiceForm(initial={"organization":org.id,"payment_method":'1',"packages":id_package, "number_of_months": 12 },user_customer=request.user)
            

        return render(request,'pricing.html', locals())
    raise Http404


def read_orders(request):
    order_items = OrderItems.objects.all().order_by("-created")
    return render(request,'admin_orders.html',locals())

actarium_apps/customers_services/templates/admin_orders.html
{% extends "asettings/settings_menu.html" %}
{% load i18n pricing %}
{% block TITLE %}Administrar Ordenes{% endblock %}


{% block bodysettings %}

	<h3>Administrar Ordenes</h3>
	<p>Espacio para administrar las ordenes que han realizado los clientes de Actarium</p>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3>{% trans 'Ordenes de servicio' %}</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<thead>
					<tr >
						<th>{% trans 'Orden' %}</th>
						<th>{% trans 'Estado' %} </th>
						<th>{% trans 'Usuario' %} </th>
						<th>{% trans 'Organización' %} </th>
						<th>{% trans '# miembros' %}</th>
						<th>{% trans '# meses' %}</th>
						<th>{% trans 'Total' %}</th>
						<th>{% trans 'Acciones' %}</th>
					</tr>
				</thead>
				<tbody>
				   {% for order_item in order_items %}
					<tr>
						<td>{{ order_item.id }}</td>
						<td>
							<span class="glyphicon {{ order_item.order.status.id|icon_status }}"></span> 
							{{ order_item.order.status.name }}
						</td>
						<td>{{ order_item.order.customer.actariumcustomers_customer.get_user.username }}</td> 
						<td>{{ order_item.customer_service.organizationservices_service.get_org.name }}</td>
						<td>{{ order_item.order_quantity }}</td>
						<td>{{ order_item.number_of_periods }}</td>
						<td>${{ order_item.get_total_price }}</td>
						<td>
							<button class="btn btn-lg btn-approve" data-toggle="modal" data-target="#myModal" data-order-id="{{ order_item.id }}"
								{% if order_item.order.status.id == 2 or order_item.order.status.id == 6 %} disabled="disabled" {% endif %}> 
								{% trans 'Aprobar' %} 
							</button>
							<button class="btn btn-lg" data-toggle="modal" data-target="#myModal" > 
								{% trans 'Rechazar' %} 
							</button>
						</td>
					</tr>
				   {% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

{%block settings_style%}
{% endblock %}

{% block settings_js %}
<script type="text/javascript" ><!--
	$(document).on("ready", function() {
		$("#settings-admin-orders").addClass("active");

		function showResponse(data){
			console.log("is_done",data.is_done,"response",data.response)
			console.dir(data)
			if(data.Error){
				setAlertError("Error", data.Error)
			}
			else if (data.is_done){
				window.top.location.href="{% url 'services:admin_orders' %}"
			}

		}

		$(".btn-approve").on("click", function(){
				order_id = $(this).attr("data-order-id");
				sendNewAjax("{% url 'services:approve_order' %}",
					{"order_id":order_id},
					showResponse,
					{"method":"post"})
			});

	});
</script>
{% endblock %}

actarium_apps/customers_services/templates/payment_summary_tpl.html
{% load i18n %}
<script type="text/template" id="paymentSummaryTpl" >
	<table  class="table" >
		<tr>
			<td> 
				{% trans 'Precio por mes' %}: 
			</td>
			<td class="text-right" >  
				$ <strong id="pricePerMonth">
					{% verbatim %}
						{{ price_per_month}}
					{% endverbatim %}
				</strong>
			</td>
		</tr>
		<tr>
			<td> 
				{% trans 'Sub total' %} 
				{% verbatim %}
						<strong>{{ number_of_months }}</strong>
				{% endverbatim %} meses : 
			</td>
			<td class="text-right">  $ <strong id="subTotal">
					{% verbatim %}
						{{ price_total_months }}
					{% endverbatim %}
				</strong>
			</td>
		</tr>
		<tr>
			<td> {% trans 'Descuento por codigo' %}: 
			</td>
			<td class="text-right">  
				- $ <strong id="discountValue">
					{% verbatim %}
						{{ discount_by_code }}
					{% endverbatim %}
				</strong>
			</td>
		</tr>
		<tr>
			<td> {% trans 'Descuento por mas de 12 meses' %}: 
			</td>
			<td class="text-right">  
				- $ <strong id="discountValue">
					{% verbatim %}
						{{ discount_by_periods }}
					{% endverbatim %}
				</strong>
			</td>
		</tr>
		<tr>
			<td> {% trans 'Total a pagar (IVA incluido):' %}: 
			</td>
			<td class="text-right"> 
				$ <strong id="totalPrice">
					{% verbatim %}
						{{ total }}
					{% endverbatim %}
				</strong>
			</td>
		</tr>
	</table>
</script>

actarium_apps/customers_services/templates/pricing.html
{% extends "organizations/menu.html" %}
{% load i18n pricing %}
{% block TITLE %}{% trans 'Precios' %}{% endblock %}
{% load humanize %}

{% block content_menu %}
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="myModalLabel">{% trans 'Actualizar paquete' %}</h4>
	      </div>
	      <form class="form-horizontal" method="POST">
		      <div class="modal-body">
		            {% csrf_token %}
		            <table id="tableForm" class="table">
		            	{{ order_members_form }}
		            </table>
		            <h4>{% trans 'Resumen' %}</h4>
		            <div id="paymentSummaryTable" >
		            </div>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cerrar' %}</button>
		        <button type="submit" class="btn btn-primary">{% trans 'Actualizar' %}</button>
		      </div>
	      </form>
	    </div>
	  </div>
	</div>
	<!-- /Modal -->


	<h3>{% trans 'Precios' %}</h3>

	{% if org %}

		<a class="btn btn-default" href="{% url 'core:read_organization_services' org.slug %}"><span class="glyphicon glyphicon-arrow-left"></span> {% trans 'Volver' %} </a>

	{% endif %}

	<p>{% trans 'Listado de los servicios disponibles' %}</p>


	<div class="panel panel-default">
		<div class="panel-heading">
			<h3>{% trans 'Paquetes predefinidos' %}</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<thead>
					<tr >
						<th>{% trans 'Opci&oacute;n' %} </th>
						<th>{% trans '# Miembros' %} </th>
						<th>{% trans 'Precio' %}</th>
						<th>{% trans 'Adquirir' %}</th>
					</tr>
				</thead>
				<tbody>
					{% for package in packages %}
						<tr>
							<td>{{ package.code }}</td>
							<td>{{ package.number_of_members }}</td>
							<td>$ {{ package.number_of_members|total_price|intcomma}} / {{ package.service.period.name }}</td>
							<td>
								<a class="btn btn-lg" href="{% url 'services:read_pricing' org.slug %}?id_package={{ package.id }}">{% trans 'Adquirir' %} </a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

	{% include "payment_summary_tpl.html" %}

{% endblock %}

{%block style_menu %}
<style>
	#tableForm th, #tableForm td{
		border: 0px;
	}
	
</style>
{% endblock %}

{% block js_menu %}
	<script src="{{ STATIC_PREFIX }}js/vendor/swig.min.js"></script>
	<script>
        $(document).ready(function(){

        	{% include "payment_summary.js" %}


            $(".org-menu-container #org-services").addClass("active")
                .find("a > span").addClass("glyphicon glyphicon-chevron-right");

            //Pricing initial options
            $('.btn-upgrade').on('click', function(){
				number_of_members = $(this).attr('data-number-of-members');
				// console.log(number_of_members)
				$('#id_number_of_members').val(number_of_members)
				payment_summary_obj.update()
			})


            //Form Actions
			$("#id_packages").on("change", function(){
				payment_summary_obj.update()
			});

			$("#id_number_of_months").on("change", function(){
				payment_summary_obj.update()
			})
			
			$("#id_discount").on("blur", function(){
				payment_summary_obj.update()
			});

			payment_summary_obj.update()

			{% if show_modal %}
				$('#myModal').modal();
			{% endif %}

			{% if error %}
				setAlertError("Error", "{{ error }}")
			{% endif %}

        });
    </script>
{% endblock %}