Actarium/urls.py
#encoding:utf-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # to change:
    url(r'^contact/', include('contact_form.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^oauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^meal/', include(admin.site.urls)),
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

for app in settings.APPS:
    try:
        appurls = __import__(app + ".urls", fromlist=['urls'])
        if hasattr(appurls, "name"):
            ns = ""
            if hasattr(appurls, "namespace"):
                ns = appurls.namespace
            urlpatterns += patterns('',
                url(r'^' + appurls.name + '/', include(appurls.urlpatterns, namespace=ns)),
            )
        else:
            urlpatterns += appurls.urlpatterns
    except Exception as e:
        # print "Error: ",app, e
        # print type(e)
        if not (str(e) =="No module named urls"):
            raise e


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

urlpatterns += patterns("",
    url(r'^$', 'actarium_apps.organizations.views.listOrgs', name="list_orgs"),
)

actarium_apps/api/urls.py
# -*- coding:utf-8 -*-

# import django elements
from django.conf.urls import patterns, include, url

# import rest_framework elements
from rest_framework.routers import DefaultRouter

# import custom elements
from .viewsets import UserViewSet


router = DefaultRouter()
router.register(r'users', UserViewSet)


name = "rest"
# namespace = 'rest_framework'

urlpatterns = patterns('',
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
)

actarium_apps/core/urls.py
from django.conf.urls import url, patterns
from .views import *
from .views_ajax import *

name = "actarium"
namespace = 'core'

urlpatterns = patterns('',
    url(r'^services/(?P<slug_org>[-\w]+)/$', read_organization_services, name='read_organization_services'),
    url(r'^get_price/$', get_total_price, name='get_total_price'),
    url(r'^get_discount_value/$', get_discount_value, name='get_discount_value'),
    url(r'^search_minutes/$', search_minutes, name='search_minutes'),
)

actarium_apps/customers_services/urls.py
from django.conf.urls import url, patterns
from .views import read_pricing, read_orders
from .views_ajax import approve_order

name = "services"
namespace='services'

urlpatterns = patterns('',
    url(r'^pricing/(?P<slug_org>[-\w]+)/$', read_pricing, name='read_pricing'),
    url(r'^admin_orders/$', read_orders, name='admin_orders'),
    url(r'^approve_order/$', approve_order, name='approve_order'),
)

actarium_apps/organizations/urls.py
from django.conf.urls import url, patterns
# name = "orgs"
urlpatterns = patterns('actarium_apps.organizations.views',
    
    url(r'^create/', 'createOrg', name="create_org"),
    url(r'^(?P<slug_org>[-\w]+)/$', 'readOrg', name="show_org"), # url(r'^(?P<slug_org>[-\w]+)/edit$', 'updateOrg', name="update_org"),
    url(r'^(?P<slug_org>[-\w]+)/delete$', 'deleteOrg', name="delete_org"),
    
    url(r'^(?P<slug_org>[-\w]+)/settings$', 'settingsOrg', name="profile_org"),
    url(r'^(?P<slug_org>[-\w]+)/team$', 'teamOrg', name="team_org"),
)
    
urlpatterns += patterns('actarium_apps.organizations.views_ajax',
    url(r'^(?P<slug_org>[-\w]+)/get-members$', 'getListMembers', name="get_users_list"),
    url(r'^(?P<slug_org>[-\w]+)/get-groups$', 'get_user_org_groups', name="get_user_org_groups"),
    url(r'^(?P<slug_org>[-\w]+)/change-role$', 'config_admin_to_org', name="config_admin_to_org"),
    url(r'^(?P<slug_org>[-\w]+)/delete-member$', 'delete_member_org', name="delete_member_org"),
    url(r'^(?P<slug_org>[-\w]+)/invite-new-member$', 'set_org_invitation', name="set_org_invitation"),
    url(r'^(?P<slug_org>[-\w]+)/create-invite-new-member$', 'create_invite_user_to_org', name="create_invite_user_to_org"),
)

actarium_apps/organizations/forms.py
#encoding:utf-8
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from .models import Organizations
from django.utils.translation import ugettext_lazy as _


class OrganizationForm(forms.ModelForm):
    name = forms.CharField(label=_(u"Nombre de Organización"),max_length=100,  widget=forms.TextInput(attrs={'placeholder': _(u'Nombre de organización'), 'autofocus': 'autofocus'}))
    description = forms.CharField(label=_(u"Descripción (opcional)"), max_length=100, help_text=_(u'Máx. 100 caractéres.'), required=False, widget=forms.TextInput(attrs={'class': '', 'placeholder': 'Descripción'}))
    image_path = forms.FileField(label=_(u"Logo (opcional)"), required=False, widget=forms.FileInput(attrs={'placeholder': _('URL del logo')}), help_text=_("No seleccionar para conservar el actual"))

    def clean_name(self):
    	name = self.cleaned_data.get('name')
    	if name.lower() in settings.RESERVED_WORDS:
    		raise ValidationError(_(u"No puedes usar este nombre para tu organización."))
    	return name

    class Meta:
        model = Organizations
        fields = ("name", "description", "image_path")

actarium_apps/organizations/views.py
#encoding:utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _
from django.conf import settings

from actarium_apps.core.utils import create_default_service
from apps.actions_log.views import saveActionLog, saveViewsLog
from apps.website.views import getGlobalVar
from actarium_apps.organizations.models import Organizations, OrganizationsUser, OrganizationsRoles
from .forms import OrganizationForm
from .utils import saveOrganization


@login_required(login_url='/account/login')
def listOrgs(request):
    organizations = request.user.organizationsuser_user.get_orgs_by_role_code("is_member")
    return render(request, "organizations/read_orgs.html", locals())

#### ORGANIZATION CRUD #####
@login_required(login_url='/account/login')
def createOrg(request):
    from actarium_apps.core.forms import PackagesForm
    from actarium_apps.core.models import Packages

    saveViewsLog(request, "apps.groups_app.views_groups.createOrg")
    ref = request.GET.get('ref') if 'ref' in request.GET else ""
    if request.method == "POST":

        package_form = PackagesForm(1, request.POST)
        form = OrganizationForm(request.POST, request.FILES)

        if form.is_valid() and form.is_multipart():
            org = form.save()
            org.set_role(request.user, is_admin=True, is_member=True, is_creator=True)

            is_created, response = create_default_service(request.user, org)
            saveActionLog(request.user, 'NEW_ORG', "name: %s" % (org.name), request.META['REMOTE_ADDR'])

            if package_form.is_valid():

                pf = package_form.cleaned_data['packages']
                if pf.code == "5":
                    return HttpResponseRedirect(org.get_absolute_url())
                else:
                    return HttpResponseRedirect(reverse("services:read_pricing",args=(org.slug,))+"?id_package="+str(pf.id))
    else:
        id_package = request.GET.get("id_package")
        form = OrganizationForm()
        package_form = PackagesForm(1,initial = {'packages': id_package })
    TRIAL_MEMBERS = getGlobalVar("TRIAL_MEMBERS")
    TRIAL_MONTH = getGlobalVar("TRIAL_MONTH")
    return render(request, "organizations/create_org.html", locals())


@login_required(login_url='/account/login')
def readOrg(request, slug_org=False):
    if slug_org:
        org = request.user.organizationsuser_user.get_org(slug=slug_org)
        if org and org.has_user_role(request.user, "is_member"):
            return render(request, "organizations/index.html", locals())
        else:
            if not settings.DEBUG:
                raise Http404
            else:
                return HttpResponse("[DEBUG=True] - Hola, soy tu padre Django. Me temo decirte que esta url la está interpretando la aplicación 'Organizations' sorry.")
    return listOrgs(request)


@login_required(login_url='/account/login')
def deleteOrg(request, slug_org):
    org = request.user.organizationsuser_user.get_org(slug=slug_org)
    if org and org.has_user_role(request.user, "is_creator"):
        if request.method == "POST" and "archive" in request.POST:
            org.is_archived = True
            org.save()
            saveActionLog(request.user, 'DEL_ORG', "name: %s" % (org.name), request.META['REMOTE_ADDR'])
            return HttpResponseRedirect(reverse("home") + "?org_archived=1")
        return render(request, "organizations/delete_org.html", locals())
    else:
        raise Http404
#### ORGANIZATION CRUD #####


@login_required(login_url='/account/login')
def settingsOrg(request, slug_org):
    org = request.user.organizationsuser_user.get_org(slug=slug_org)
    user_is_admin = org.has_user_role(request.user, "is_admin")
    if org and ('edit' in request.GET) and user_is_admin:
        update = True
        if request.method == "POST":
            form = OrganizationForm(request.POST, request.FILES, instance=org)
            if form.is_valid() and form.is_multipart():
                form.save()
                updated = saveActionLog(request.user, 'EDIT_ORG', "name: %s" % (form.cleaned_data['name']), request.META['REMOTE_ADDR'])
                return HttpResponseRedirect(reverse("profile_org", args=(org.slug,)))
        else:
            form = OrganizationForm(instance=org)
    elif org and org.has_user_role(request.user, "is_member"):
        update = False
        current_members = org.get_num_members()
        max_members = org.organizationservices_organization.get_max_num_members()
        total = int(current_members)*100/int(max_members)
    else:
        raise Http404
    return render(request, "organizations/profile_org.html", locals())


@login_required(login_url='/account/login')
def teamOrg(request, slug_org):
    org = request.user.organizationsuser_user.get_org(slug=slug_org)
    if org:
        is_org_admin = org.has_user_role(request.user, "is_admin") # this var is needed in templates
        if is_org_admin or org.has_user_role(request.user, "is_member"):
            current_members = org.get_num_members()
            max_members = org.organizationservices_organization.get_max_num_members()
            total = int(current_members)*100/int(max_members)
            return render(request, "organizations/team_org.html", locals())
    raise Http404

organization/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

from organization.models import organizations

@login_required(login_url='/account/login')
def list(request):
    '''
    lista las organizaciones del usuario registrado
    '''
    if request.user.is_authenticated():
        org = organizations.objects.order_by("id")
        ctx = {'TITLE':"Actarium","org":org}
    else:
        ctx = {'TITLE':"Actarium"}
    return render_to_response('organization/list.html',{}, context_instance = RequestContext(request))

@login_required(login_url='/account/login')
def new(request):
    '''
    crea una nueva organizacion 
    '''
    return render_to_response('organization/new.html',{}, context_instance = RequestContext(request))

@login_required(login_url='/account/login')
def listMinutes(request):
    '''
    crea una nueva organizacion 
    '''
    return render_to_response('organization/listAct.html',{}, context_instance = RequestContext(request))

actarium_apps/organizations/templates/organizations/create_org.html
{% extends "base.html" %}
{% load gravatartag i18n %}
{% block TITLE %}{% trans 'Crear organización' %}{% endblock %}

{%block body%}
<article>
    <div class="row-fluid">
 <!--        <div class="white-box-container info-box" id="try-trial">
            <div id="giftbox"></div>
            {% trans 'Pruébalo' %} <h2>{% trans '¡GRATIS!' %}</h2> {% trans 'por 30 días' %}
            <p>{% blocktrans with members=TRIAL_MEMBERS months=TRIAL_MONTH mon=TRIAL_MONTH|pluralize mem=TRIAL_MEMBERS|pluralize %}Crea una organización trial, puedes invitar a {{ members }} miembro{{ mem }} y probar los beneficios de Actarium gratis por {{ months }} mes{{ mon }}.{% endblocktrans %}*</p>
        </div> -->
        <div class="white-box-container info-box message-box">
            <h3>{% trans 'Crear organización' %}</h3>
            <hr>
            <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="">
                {% csrf_token %}
                {{ package_form.as_p }}
                {{ form.as_p }}
                <br><br>
                <input type="hidden" value="{{ref}}" name="ref" >
                <a href="{% url 'home' %}" class="btn"><span class="glyphicon glyphicon-arrow-left"></span> {% trans 'Volver' %}</a>
                <input type="submit" class="btn btn-large btn-info" value="{% trans 'Crear organización' %}" >
            </form>
        </div>
    	<div class="white-box-container info-box" id="">
            <!-- <p>* {% trans 'No te preocupes, puedes ampliar tus cupos cuando quieras, tu información seguirá ahí :)' %}</p> -->
            <p class="lead">{% trans 'Necesita más miembros?' %} <a href="/contact">{% trans 'Escríbanos aquí' %}</a></p>
        </div>
    </div>
</article>
{%endblock%}
{%block style%}
<link href='https://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
<style>
    @font-face{font-family: HelveticaNeueLT;src: url({{ STATIC_URL }}fonts/HELVETICANEUELTSTD-TH.OTF);}
    @font-face{font-family: Bebas;src: url({{ STATIC_URL }}fonts/BEBAS.TTF);}
	.white-box-container{text-align: center; margin: 0 auto;margin-bottom: 20px !important;width: 50%; font-size: 16px !important;text-align: left;font-family: 'Titillium Web' !important}
    h3, .btn{font-family: 'Titillium Web' !important;}
    #try-trial{font-family: HelveticaNeueLT;}
    form input{padding: 7px 10px !important;font-size: 14px !important;}
    form input[type='file']{width: 60%;}
    form label{/*display: block;*/width: 40%;}
    form select{width: 210px;margin-left: 0 !important;}
    .helptext {display: inline-block;margin-left: 4px;}
</style>
{%endblock%}

{% block js %}
<script>
    $(document).ready(function(){

    });
</script>
{% endblock %}

actarium_apps/organizations/templates/organizations/delete_org.html
{% extends "base.html" %}
{% load gravatartag i18n %}
{% block TITLE %}{% trans 'Eliminar organización' %}{% endblock %}

{%block body%}
<article>
	
    <header >
        <div class="row">
            <div class="col-md-8">
                <div class="menu-icons icons-page icon-groups"></div>
                <h3>{% trans 'Eliminar organización' %}</h3>
            </div>
        </div>
    </header>
    <hr/>
    <div class="row-fluid">
        <div class="white-box-container">
            <h4>{% trans 'Archivar organización' %}</h4>
            <p>{% trans 'Las organizaciones no se pueden eliminar del todo.' %}</p>
            <p>{% trans 'Puedes archivar ésta organización para que desaparezca de tu lista de organizaciones.' %}</p>
            <p>{% trans '¿Seguro que desea archivar esta organización?' %}</p>
            <form class="" enctype="multipart/form-data" method="POST" action="">
                {% csrf_token %}
                <input type="hidden" name="archive" value="true">
    			<a href="{% url 'profile_org' org.slug %}" class="btn btn-large"><span class="glyphicon glyphicon-arrow-left"></span> {% trans 'Cancelar' %}</a>
                <button type="submit" class="btn btn-large btn-warning db"><span class="glyphicon glyphicon-remove"></span> {% trans 'Archivar' %}</button>
            </form>
    	</div>
    </div>
</article>
{%endblock%}
{%block style%}
<style>
	.white-box-container{width: 40%;margin: 0 auto;}
</style>
{%endblock%}

{% block js %}
<script>
    $(document).ready(function(){

    });
</script>
{% endblock %}

actarium_apps/organizations/templates/organizations/form_org.html
{% load i18n %}
    <form class="form-horizontal" enctype="multipart/form-data" method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <img src="{{ org.image_path.url_100x100 }}" alt="{{ org.name }}"><hr>
        <input type="hidden" value="{{ref}}" name="ref" >
        <a href="{% url 'profile_org' org.slug %}" class="btn btn-large"><span class="glyphicon glyphicon-arrow-left"></span> {% trans 'Cancelar' %}</a>
        <input type="submit" class="btn btn-large btn-info db" value="{% trans 'Actualizar' %}" >
    </form>

actarium_apps/organizations/templates/organizations/group_list.html
{% load i18n orgs_ttag %}
{% for g in org.get_groups|only_groups_of:user %}
<a href="{{ g.get_absolute_url }}">
    <div class="group-preview">
        <!-- <span class="pull-right group-notifications glyphicon glyphicon-bell"></span> -->
        <div class="group-circle">
        <span class="group-members-num" title="{{ g.get_num_members }} {% trans 'miembros' %}">{{ g.get_num_members }}</span>
        </div>
        <div class="group-permissions">
            <span title="{% trans 'Administrador de grupo' %}" class="glyphicon glyphicon-wrench"></span>
            <span title="{% trans 'Puedes redactar actas' %}" class="glyphicon glyphicon-pencil"></span>
            <span title="{% trans 'Apareces en las actas' %}" class="glyphicon glyphicon-user"></span>
        </div>
        <div class="group-name" title="{{ g.name }}"><p>{{ g.name }}</p></div>
    </div>
</a>
{% empty %}
<p>{% trans 'No tienes ningún grupo en tu organización' %} <strong>{{ org.name }}</strong></p>
<p>{% trans 'Organiza a tu equipo de trabajo en grupos como "Comité financiero", "Consejo Administrativo", etc.' %}</p>
{% endfor %}
{% if user_is_admin %}
<a href="{% url 'new_group' %}?org={{ org.id }}">
    <div class="group-preview btn-new-group">
        <div class="group-circle group-circle-plus">
            <span class="group-members-num btn-create-group" ><i class="glyphicon glyphicon-plus"></i></span>
        </div>
        <div class="group-permissions">
            <span class="glyphicon"></span>
        </div>
        <div class="group-name" title="{{ g.name }}">{% trans 'Crear grupo' %}</div>
    </div>
</a>
{% endif %}

actarium_apps/organizations/templates/organizations/index.html
{% extends "organizations/menu.html" %}
{% load i18n orgs_ttag %}
{% block TITLE %}{% trans 'Home' %}{% endblock %}

{% block content_menu %}
{% has_role "user" "org" "is_admin" as user_is_admin %}
    <div>
        {% include "organizations/group_list.html" %}
    </div>
{% endblock %}

{% block style_menu %}
<style>

</style>
{% endblock %}

{% block js_menu %}
    <script>
        $(document).ready(function(){
            $(".org-menu-container #org-groups").addClass("active")
                .find("a > span").addClass("glyphicon glyphicon-chevron-right");
            $(".group-permissions > span, .group-name, .group-members-num").tooltip();
        });
    </script>
{% endblock %}

actarium_apps/organizations/templates/organizations/menu.html
{% extends "base.html" %}
{% load i18n orgs_ttag %}
{% block TITLE %}{% trans 'Home' %}{% endblock %}
{% block body %}
{% has_role "user" "org" "is_admin" as user_is_admin %}
<article>
    <div class="row-fluid org-menu-container">
        <nav class="nav-menu col-md-2 col-sm-3" >
            <div class="bs-docs-sidebar">
                <ul class="nav nav-list bs-docs-sidenav">
                    <li>
                        <div class="box" id="org-info">
                            <span class="pull-left"><img class="img-circle b" src="{{ org.get_short_icon }}" alt="{{ org.name }}"> </span>
                            <span class="pull-left" id="org-info-text">
                                <h5>{{ org.name|truncatechars:16 }}</h5>
                                {% if user_is_admin %}
                                <p><a href="{% url 'profile_org' org.slug %}?edit">{% trans 'Editar' %}</a></p>
                                {% else %}
                                <p>{{ org.description|truncatechars:26 }}</p>
                                {% endif %}
                            </span>
                        </div>
                    </li>
                    <li id="org-groups" ><a href="{{ org.get_absolute_url }}"><span></span>{% trans 'Grupos' %}</a></li>
                    <li id="org-team"><a href="{% url 'team_org' org.slug %}"><span></span>{% trans 'Miembros' %}</a></li>
                    <li id="org-profile"><a href="{% url 'profile_org' org.slug %}"><span></span>{% trans 'Configuración' %}</a></li>
                    <li id="org-services" ><a href="{% url 'core:read_organization_services' org.slug %}"><span></span>{% trans 'Servicios' %}</a></li>
                    
                </ul>
            </div>
        </nav>
        <div id="content_menu" class="col-md-10 col-sm-9">
            <div class="bt bb">
                {% block content_menu %}{% endblock %}
            </div>
        </div>
    </div>
</article>
{% endblock %}

{% block style %}
<style>
    .org-menu-container > nav{padding: 0;margin: 0}
    .org-menu-container nav.nav-menu ul.nav{margin: 0;}
    .org-menu-container .glyphicon-chevron-right{float: right;}
    .bs-docs-sidenav{width: auto;}
    .breadcrumb{background: none;margin-top: 3px;}
    /*#content_menu{height: 100%;min-height: 200px;overflow: hidden;}*/
    #content_menu > div{height: 100%;min-height: 200px;padding: 5px;}
    .bs-docs-sidenav > li > a{border:none;}
    #topbar-btn-logo{padding-right: 72px;/*padding-right: 37px;padding-left: 58px;*/padding-right: 62px;
padding-left: 31px;}
    #org-info{margin-bottom: 5px;padding-left: 10px;}
    #org-info-text{margin: 2px 0;margin-left:7px}
    #org-info-text h5{margin: 0;}
    #org-info-text a{text-decoration: underline;}
    .btn .caret{margin: 0 !important;}
</style>
{% block style_menu %}{% endblock %}
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function(){
            $("#topbar-group-name").html('<ol class="breadcrumb"><li><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></li></ol>')
            // $("").tooltip();
        });
    </script>
    {% block js_menu %}{% endblock %}
{% endblock %}

actarium_apps/organizations/templates/organizations/profile_org.html
{% extends "organizations/menu.html" %}
{% load i18n orgs_ttag %}
{% block TITLE %}{% trans 'Home' %}{% endblock %}
{% block content_menu %}
{% has_role "user" "org" "is_creator" as user_is_creator %}
    <div class="org-profile">
	{% if update %}
    	{% include "organizations/form_org.html" %}
    {% else %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans 'Información de organización' %}</h3>
            </div>
            <div class="panel-body">
                <span class="pull-left "><img class="img-circle b" src="{{ org.image_path.url_100x100 }}" alt="{{ org.name }}"></span>
                <div class="pull-left org-info">
                    <h3>{{ org.name }}</h3>
                    <p>{{ org.description }}</p>
                    <div class="box org-num-members">
                        <div class="box">
                            <span class="pull-left">{% trans 'Miembros' %}</span>
                            <span class="pull-right">{{ current_members }} {% trans 'de' %} {{ max_members }}</span>
                        </div>
                        <div class="progress">
                          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" id="org-num-members">
                            <span class="sr-only"></span>
                          </div>
                        </div>
                        <a class="btn" href="{% url 'services:read_pricing' org.slug %}"><span class="glyphicon glyphicon-user"></span> {% trans 'Actualizar miembros' %}</a>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                {% if user_is_admin %}
                <a href="{% url 'profile_org' org.slug %}?edit" class="btn"><span class="glyphicon glyphicon-edit"></span> {% trans 'Editar perfil' %}</a>
                {% if user_is_creator %}<a href="{% url 'delete_org' org.slug %}" class="btn"><span class="glyphicon glyphicon-remove"></span> {% trans 'Archivar organización' %}</a>{% endif %}
                {% endif %}
            </div>
        </div>
        
	{% endif %}
    </div>
{% endblock %}

{% block style_menu %}
<style>
	.org-profile form label{width: 160px;}
	.org-profile .org-info{margin-left: 10px;min-width: 180px;}
    .org-profile .org-info h3{margin-top: 0}
	.org-profile .org-num-members{max-width: 200px}
    #content_menu > div{border:none;}
</style>
{% endblock %}
{% block js_menu %}
    <script>
        $(document).ready(function(){
            $(".org-menu-container #org-profile").addClass("active")
                .find("a > span").addClass("glyphicon glyphicon-chevron-right");
            {% if updated %}
            	setAlertMessage("{% trans 'Información actualizada' %}","{% trans 'La información de su organización ha sido actualizada con éxito' %}");
            {% endif %}
            $("#org-num-members").css({"width": {{ total }} + "%"});
        });
    </script>
{% endblock %}

actarium_apps/organizations/templates/organizations/template.html
{% extends "organizations/menu.html" %}
{% load i18n has_role %}
{% block TITLE %}{% trans 'Home' %}{% endblock %}

{% block content_menu %}
    <div>asd
    </div>
{% endblock %}

{% block style_menu %}
<style>

</style>
{% endblock %}

{% block js_menu %}
    <script>
        $(document).ready(function(){
            $(".org-menu-container #org-groups").addClass("active")
                .find("a > span").addClass("glyphicon glyphicon-chevron-right");
        });
    </script>
{% endblock %}

actarium_apps/organizations/templates/organizations/update_org.html
{% extends "base.html" %}
{% load gravatartag i18n %}
{% block TITLE %}{% trans 'Editar organización' %}{% endblock %}

{%block body%}
<article>
    <header >
        <div class="row">
            <div class="col-md-8">
                <div class="menu-icons icons-page icon-groups"></div>
                <h3>{% trans 'Editar organización' %}</h3>
            </div>
        </div>
    </header>
    <hr/>
    <div class="row-fluid">
    	<!-- <p>....</p> -->
        <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="">
        	{% csrf_token %}
        	<div class="white-box-container">
            	{{ form.as_p }}<br><br>
    			<input type="hidden" value="{{ref}}" name="ref" >
    			<a href="{% url 'show_org' org.slug %}" class="btn btn-large"><span class="glyphicon glyphicon-arrow-left"></span> {% trans 'Volver' %}</a>
    			<input type="submit" class="btn btn-large btn-info db" value="{% trans 'Actualizar' %}" >
        	</div>
    	</form>
    </div>
</article>
{%endblock%}
{%block style%}
<style>
	.white-box-container{width: 40%;margin: 0 auto;}
</style>
{%endblock%}

{% block js %}
<script>
    $(document).ready(function(){

    });
</script>
{% endblock %}